name: Spellcheck
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@0.6.0
      name: Spellcheck
